/**
 ******************************************************************************
 * @file           :  input_task.h
 * @brief          :  Input event aggregation task for button and rotary encoder
 *
 * @details        :  FreeRTOS task that continuously polls physical input
 *                    devices (three pushbuttons and rotary encoder) and
 *                    converts their state changes into input events for other
 *                    subsystems via message queue. Debounces button presses
 *                    and accumulates rotary encoder steps. Runs at 25ms
 *                    polling interval with GPIO interrupt handlers for state
 *                    change acceleration.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 MiraTherm.
 * This file is licensed under GPL-3.0 License.
 * For details, see the LICENSE file in the project root directory.
 *
 ******************************************************************************
 */

#ifndef CORE_INC_INPUT_TASK_H
#define CORE_INC_INPUT_TASK_H

#include "buttons.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @typedef Input2VPEventTypeDef
 *
 * @brief  Input event types for UI presentation layer
 *
 * @details  Enumerates all input events generated by the input task:
 *           - EVT_LEFT_BTN: Left pushbutton press/release
 *           - EVT_MIDDLE_BTN: Center pushbutton press/release
 *           - EVT_RIGHT_BTN: Right pushbutton press/release
 *           - EVT_CTRL_WHEEL_DELTA: Rotary encoder incremental step (+/-)
 */
typedef enum {
  EVT_LEFT_BTN = 0,      /**< Left button event */
  EVT_MIDDLE_BTN,        /**< Middle/center button event */
  EVT_RIGHT_BTN,         /**< Right button event */
  EVT_CTRL_WHEEL_DELTA   /**< Rotary encoder delta (step count) */
} Input2VPEventTypeDef;

/**
 * @typedef Input2VPEvent_t
 *
 * @brief  Input event structure for message queue
 *
 * @details  Complete input event with type, button action state, rotary
 *           encoder step delta (positive=clockwise, negative=counter-clockwise),
 *           and timestamp for event ordering and latency tracking.
 */
typedef struct {
  Input2VPEventTypeDef type;  /**< Event type (button/encoder) */
  button_action_t button_action; /**< BUTTON_ACTION_PRESSED or BUTTON_ACTION_RELEASED */
  int16_t delta;              /**< Rotary encoder delta steps (encoder events only) */
  uint32_t timestamp;         /**< Milliseconds since system start (HAL_GetTick) */
} Input2VPEvent_t;

/**
 * @typedef InputTaskArgsTypeDef
 *
 * @brief  Arguments for input task startup
 *
 * @details  Contains the message queue handle for posting input events.
 *           Passed to task via osThreadNew() or equivalent FreeRTOS API.
 */
typedef struct {
  osMessageQueueId_t input2vp_event_queue; /**< Queue for input events to view presenter */
} InputTaskArgsTypeDef;

/**
 * @def INPUT_TASK_STACK_SIZE
 *
 * @brief  FreeRTOS task stack size in bytes
 *
 * @details  Stack allocation for input task (2048 bytes).
 */
#define INPUT_TASK_STACK_SIZE (512U * 4U)

/**
 * @brief  Start the input event aggregation task
 *
 * @details  Initializes button driver with debounce timers and rotary encoder
 *           with TIM2 encoder mode. Begins continuous polling at 25ms intervals
 *           to read button states and encoder deltas. Posts events to queue
 *           whenever state changes are detected.
 *
 * @param  argument  Pointer to InputTaskArgsTypeDef with queue handle
 *
 * @return void (never returns; runs until RTOS shutdown)
 *
 * @note   Initialize buttons and rotary encoder peripherals before calling.
 *
 * @see    Input2VPEventTypeDef, InputTaskArgsTypeDef
 */
void StartInputTask(void *argument);

#ifdef __cplusplus
}
#endif

#endif /* CORE_INC_INPUT_TASK_H */